### ISSUE TITLE
Turning this into a crate

### ISSUE THREAD

**Issue by sstadick** [dcjones/coitrees#1]
Hi! I've been working on an interval tree crate, rust-lapper. Are you planning on turning this into a library / crate? If not, do you mind if I do?

**Comment by sstadick** [comment]
As to benchmarking, what I would like do, once it's been wrapped up as a library, is implement a similar benchmark as used here: https://github.com/brentp/nim-cgranges/blob/master/tests/speed2.nim, which is what I've used for rust-lapper as well to compare against two different NCList implementations, see benchmark [here](https://github.com/sstadick/rust-lapper/blob/master/benches/lapper_benchmark.rs).

**Comment by sstadick** [comment]
Lastly, for a library version of this, I'd want to do roughly the same thing as rust-lapper, which is to have a find method that returns and iterator, allowing maximal flexibility. And possibly a seek method queries that are happening in order (but this depends on the coitree implementation, which I don't fully grok yet).

Regardless, this is a super awesome implementation you have, thanks for putting it our here! I understand it's MIT License and all, but I'd feel too guilty just copying your code without at least checking in / seeing if you have any suggestions first.

**Comment by dcjones** [comment]
I'm not sure if you still interested in this, but I have started tinkering with this code again and just saw your issue. It's refactored into a proper module now, and though I haven't added an iterator yet, there is a is general purpose query method now that takes a callback function that's called on every overlapping node (like `tree.query(start, end, |interval| ...`). I'll probably turn this into a crate, if that helps.

I would be interested to see how it compares with lapper!

**Comment by sstadick** [comment]
This is great news! I'm planning on eventually putting together a
submission for lh3's biofast, which seems like a good standard way to
compare things.
