### ISSUE TITLE
Push 3.0 to Crates.io? 

### ISSUE THREAD

**Issue by vsbuffalo** [dcjones/coitrees#15]
I'd love to use coitrees in a project, and was stumped why I couldn't import `Interval`. It looks to be caused by an older version (2.1) only being available on [crates.io](https://crates.io/crates/coitrees). Is there a plan to push the most recent 3.0 version there? 

Thanks for creating coitrees, it looks great!

**Comment by dcjones** [comment]
Thanks for the reminder! I had simply just forgotten to push to crates. 0.3.0 is there now.
